version: '3.8'

services:
  flask_app:
    build:
      context: flask_app
      dockerfile: Dockerfile
    image: flask
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:////instance/db
    volumes:
      - instance:/instance

  model_api:
    build:
      context: model_api
      dockerfile: Dockerfile
    image: modelapi
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////instance/db
    volumes:
      - instance:/instance

  reqwiz_bot:
    build:
      context: reqwiz_bot
      dockerfile: Dockerfile
    image: pocl_bot
    environment:
      - DATABASE_URL=sqlite:////instance/db
    volumes:
      - instance:/instance

volumes:
  instance: